<?php
function super_hero_theme($existing, $type, $theme, $path){
    return [
        'hero_list' => [
            'variables' => [
                'items' =>[],
                'title' => ''
            ]
        ]
    ];
}

function super_hero_entity_presave(Drupal\Core\Entity\EntityInterface $entity){
    if($entity->bundle()=='article'){
       drupal_set_message('calling presave hook');
    }
}